import{i as w}from"./assets/vendor-BlI1llIz.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const L="49366841-2722787d336af87d57ebdc2bd",b="https://pixabay.com/api/",u=async(t,s)=>{const r=await axios.get(b,{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}});if(r.status!==200)throw new Error("Failed to fetch images.");return r.data.hits},p=(t,s=!1)=>{const r=document.querySelector(".gallery");if(t.length===0){q("Sorry, there are no images matching your search query. Please try again!");return}const a=t.map(({webformatURL:e,largeImageURL:o,tags:n,likes:m,views:f,comments:g,downloads:h})=>`
        <li>
            <a href="${o}" class="gallery__item">
                <img src="${e}" alt="${n}" loading="lazy" />
            </a>
            <div class="info">
                <p>Likes: <span>${m}</span></p>
                <p>Views: <span>${f}</span></p>
                <p>Comments: <span>${g}</span></p>
                <p>Downloads: <span>${h}</span></p>
            </div>
        </li>
    `).join("");s?r.insertAdjacentHTML("beforeend",a):r.innerHTML=a},y=()=>{document.querySelector(".loader").style.display="block"},i=()=>{document.querySelector(".loader").style.display="none"},q=t=>{w.error({title:"Error",message:t,position:"topRight"})};let l=1,d="";const v=document.querySelector(".form"),c=document.querySelector(".load-more"),S=document.querySelector('input[name="search-text"]');v.addEventListener("submit",async t=>{t.preventDefault();const s=t.target.elements["search-text"].value.trim();if(s){d=s,l=1,c.style.display="none",y();try{const r=await u(d,l);i(),p(r,!1),r.length>0&&(c.style.display="block")}catch(r){i(),console.error("Error fetching images:",r),showMessage("Failed to fetch images. Please try again later.")}finally{S.value=""}}});c.addEventListener("click",async()=>{l+=1,y();try{const t=await u(d,l);if(i(),t.length>0){p(t,!0);const r=document.querySelectorAll(".gallery li")[0].getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}else c.style.display="none",showMessage("We're sorry, but you've reached the end of search results.")}catch(t){i(),console.error("Error fetching images:",t),showMessage("Failed to fetch images. Please try again later.")}});
//# sourceMappingURL=index.js.map
