import{i as q,S as w}from"./assets/vendor-DpVPnhEv.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const S="49366841-2722787d336af87d57ebdc2bd",v="https://pixabay.com/api/",f=async(e,s)=>{const r=await axios.get(v,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}});if(r.status!==200)throw new Error("Failed to fetch images.");return r.data.hits};let d;const p=(e,s=!1)=>{const r=document.querySelector(".gallery");if(e.length===0){i("Sorry, there are no images matching your search query. Please try again!");return}const a=e.map(({webformatURL:t,largeImageURL:o,tags:n,likes:g,views:h,comments:L,downloads:b})=>`
        <li>
            <a href="${o}" class="gallery__item">
                <img src="${t}" alt="${n}" loading="lazy" />
            </a>
            <div class="info">
                <p>Likes: <span>${g}</span></p>
                <p>Views: <span>${h}</span></p>
                <p>Comments: <span>${L}</span></p>
                <p>Downloads: <span>${b}</span></p>
            </div>
        </li>
    `).join("");s?r.insertAdjacentHTML("beforeend",a):r.innerHTML=a,d?d.refresh():d=new w(".gallery a",{})},m=()=>{document.querySelector(".loader").style.display="block"},l=()=>{document.querySelector(".loader").style.display="none"},i=e=>{q.error({title:"Error",message:e,position:"topRight"})},P=()=>{const e=document.querySelector(".gallery");e.innerHTML=""};let c=1,y="";const E=document.querySelector(".form"),u=document.querySelector(".load-more"),I=document.querySelector('input[name="search-text"]');E.addEventListener("submit",async e=>{e.preventDefault();const s=e.target.elements["search-text"].value.trim();if(s){y=s,c=1,u.style.display="none",m();try{const r=await f(y,c);if(l(),P(),r.length===0){i("No images found. Please try a different query.");return}p(r,!1),r.length>0&&(u.style.display="block")}catch(r){l(),console.error("Error fetching images:",r),i("Failed to fetch images. Please try again later.")}finally{I.value=""}}});u.addEventListener("click",async()=>{c+=1,m();try{const e=await f(y,c);if(l(),e.length>0){p(e,!0);const r=document.querySelectorAll(".gallery li")[0].getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}else u.style.display="none",i("We're sorry, but you've reached the end of search results.")}catch(e){l(),console.error("Error fetching images:",e),i("Failed to fetch images. Please try again later.")}});
//# sourceMappingURL=index.js.map
