import{i as q,S}from"./assets/vendor-DpVPnhEv.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(r){if(r.ep)return;r.ep=!0;const t=o(r);fetch(r.href,t)}})();const w="49366841-2722787d336af87d57ebdc2bd",P="https://pixabay.com/api/",y=async(e,s)=>{const o=await axios.get(P,{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}});if(o.status!==200)throw new Error("Failed to fetch images.");return o.data.hits};let d;const f=(e,s=!1)=>{const o=document.querySelector(".gallery");if(e.length===0){l("Sorry, there are no images matching your search query. Please try again!");return}const a=e.map(({webformatURL:r,largeImageURL:t,tags:n,likes:g,views:h,comments:L,downloads:b})=>`
        <li>
            <a href="${t}" class="gallery__item">
                <img src="${r}" alt="${n}" loading="lazy" />
            </a>
            <div class="info">
                <p>Likes: <span>${g}</span></p>
                <p>Views: <span>${h}</span></p>
                <p>Comments: <span>${L}</span></p>
                <p>Downloads: <span>${b}</span></p>
            </div>
        </li>
    `).join("");s?o.insertAdjacentHTML("beforeend",a):o.innerHTML=a,d?d.refresh():d=new S(".gallery a",{})},p=()=>{document.querySelector(".loader").style.display="block"},m=()=>{document.querySelector(".loader").style.display="none"},l=e=>{q.error({title:"Error",message:e,position:"topRight"})},v=()=>{const e=document.querySelector(".gallery");e.innerHTML=""};let c=1,u="";const E=document.querySelector(".form"),i=document.querySelector(".load-more"),$=document.querySelector('input[name="search-text"]');E.addEventListener("submit",async e=>{e.preventDefault();const s=e.target.elements["search-text"].value.trim();if(s){u=s,c=1,i.style.display="none",v(),p();try{const o=await y(u,c);if(o.length===0){l("No images found. Please try a different query.");return}f(o,!1),i.style.display="block"}catch(o){console.error("Error fetching images:",o),l("Failed to fetch images. Please try again later.")}finally{m(),$.value=""}}});i.addEventListener("click",async()=>{c+=1,i.style.display="none",p();try{const e=await y(u,c);e.length>0?(f(e,!0),i.style.display="block"):l("We're sorry, but you've reached the end of search results.")}catch(e){console.error("Error fetching images:",e),l("Failed to fetch images. Please try again later.")}finally{m()}});
//# sourceMappingURL=index.js.map
